# Generated by Django 3.2 on 2023-09-24 11:16

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=254, unique=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=254, unique=True, verbose_name='Фамилия пользователя')),
                ('role', models.TextField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], max_length=50, verbose_name='Пользовательская роль юзера')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
