# Локальный запуск образа

version: '3'

# Перечень volume:
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    depends_on:
      - db
    restart: always
    build:
      context: ../backend/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/

  frontend:
    container_name: foodgram_frontend
    build: 
      context: ../frontend/
      dockerfile: Dockerfile
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    container_name: foodgram_gateway
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: ../nginx/local/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ../frontend/build:/usr/share/nginx/html/

    ports:
      - "80:80"
