# Локальный запуск образа

version: '3'

# Перечень volume:
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: :13.0-alpine
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    build: ../frontend/
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
  gateway:
    build: ./
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ../frontend/build:/usr/share/nginx/html/

    ports:
      - "80:80"