version: '3'

volumes:
  static:
  backend_static:
  backend_media:
  pg_data:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    image: dpavlen/foodgram_backend
    depends_on:
      - db
    restart: always
    env_file: .env
    volumes:
      - backend_static/app/static/
      - backend_media:/app/media

  frontend:
    container_name: foodgram_frontend
    image: dpavlen/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/app/result_build/build
  
  gateway:
    container_name: foodgram_gateway
    depends_on:
      - backend
      - frontend
    restart: always
    image: dpavlen/foodgram_gateway
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media

    ports:
      - 8600:80
