# Generated by Django 3.2 on 2023-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='recipes',
                through='recipes.CompositionOfDish',
                to='recipes.Ingredient',
                verbose_name='Состав блюда'),
        ),
    ]
