# Generated by Django 3.2 on 2023-10-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositionofdish',
            options={
                'verbose_name': 'Состав блюда | Ингредиент в рецепте',
                'verbose_name_plural': 'Состав блюда | Ингредиенты в рецепте'},
        ),
        migrations.AlterField(
            model_name='compositionofdish',
            name='ingredient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.ingredient',
                verbose_name='Ингредиенты в рецепте'),
        ),
        migrations.AlterField(
            model_name='compositionofdish',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='composition_list',
                to='recipes.recipe',
                verbose_name='Рецепты'),
        ),
    ]
