# Generated by Django 3.2 on 2023-10-11 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Ввведите время приготовления блюда', validators=[django.core.validators.MinValueValidator(1, message='Время приготовления блюда должно быть не менее 1 минут.'), django.core.validators.MaxValueValidator(1000, message='Время приготовления блюда не превышает более 1000 минут.')], verbose_name='Время приготовления блюда'),
        ),
        migrations.AddConstraint(
            model_name='compositionofdish',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_in_recipe'),
        ),
    ]
