# Generated by Django 3.2 on 2023-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231011_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Добавьте рецепт', upload_to='recipes/images', verbose_name='Изображение рецепта'),
        ),
    ]
