# Generated by Django 3.2 on 2023-10-07 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionofdish',
            name='amount',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиетов в блюде должно быть не меньше 1.'), django.core.validators.MaxValueValidator(100, message='Максимально количество ингредиетов в блюде не превышает 100.')], verbose_name='Количество ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте рецепт', upload_to='recipes/images', verbose_name='Изображение рецепта'),
        ),
    ]
