# Generated by Django 3.2 on 2023-10-06 12:18

import django.core.validators
from django.db import migrations, models
import recipes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionofdish',
            name='amount',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(recipes.utils.Lenght['MIN_COOKING_TIME'], message='Минимальное количество ингредиетов в блюде должно быть не меньше 1.'), django.core.validators.MaxValueValidator(recipes.utils.Lenght['MAX_AMOUNT_INREDIENT'], message='Максимально количество ингредиетов в блюде не превышает 100.')], verbose_name='Количество ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте рецепт', upload_to='recipes/images', verbose_name='Изображение рецепта'),
        ),
    ]
