# Generated by Django 3.2 on 2023-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20231007_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(
                fields=(
                    'name',
                    'measurement_unit'),
                name='unique_measurement_unit'),
        ),
    ]
