# Generated by Django 3.2 on 2023-10-03 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20231003_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sub', models.DateTimeField(
                    auto_now_add=True, verbose_name='Дата создания подписки')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='subscribe',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор рецепта')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='subscription',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(
                fields=('user', 'author'), name='unique_subscription'),
        ),
    ]
