# Generated by Django 3.2 on 2023-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20231003_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=True,
                max_length=254,
                verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True,
                max_length=254,
                verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(
                choices=[
                    ('user',
                     'User'),
                    ('moderator',
                     'Moderator'),
                    ('admin',
                     'Admin')],
                default='user',
                max_length=150,
                verbose_name='Пользовательская роль юзера'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=254,
                unique=True,
                verbose_name='Логин пользователя'),
        ),
    ]
